name: Copiar Usando Crontab

on:
  schedule:
    - cron: '*/5 * * * *'  # Ejecutar cada 5 minutos
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Copiar fichero en el VPS
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOSTNAME: ${{ secrets.IP_ADDRESS }}
        USER_NAME: ${{ secrets.USER_NAME }}
      run: |      
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem -p 9122 $USER_NAME@$HOSTNAME '
          FILENAME="/home/PruebaAnsible/testing-github/testing-$(date +%d-%m-%Y)-$(date +%I-%M%p)"
          touch "$FILENAME"
          echo "Archivo creado: $FILENAME"
        '
